/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HZ14.c                                                *
* Font:        ËÎÌו                                                  *
* Height:      14                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  14                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x8FC7 (36807)                                *
* Character enabled:   0x6D41 (27969)                                *
* Character enabled:   0x6A21 (27169)                                *
* Character enabled:   0x5F0F (24335)                                *
* Character enabled:   0x8D77 (36215)                                *
* Character enabled:   0x59CB (22987)                                *
* Character enabled:   0x7535 (30005)                                *
* Character enabled:   0x538B (21387)                                *
* Character enabled:   0x95E8 (38376)                                *
* Character enabled:   0x69DB (27099)                                *
* Character enabled:   0x6B65 (27493)                                *
* Character enabled:   0x8FDB (36827)                                *
* Character enabled:   0x65F6 (26102)                                *
* Character enabled:   0x95F4 (38388)                                *
* Character enabled:   0x8D1F (36127)                                *
* Character enabled:   0x8F7D (36733)                                *
* Character enabled:   0x77ED (30701)                                *
* Character enabled:   0x8DEF (36335)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHZ14;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_538B[ 26] = { /* code 538B */
  __XXXXXX,XXXXX___,
  __X_____,________,
  __X____X,________,
  __X____X,________,
  __X____X,________,
  __X_XXXX,XXXX____,
  __X____X,________,
  __X____X,________,
  __X____X,__X_____,
  __X____X,___X____,
  _X_____X,___X____,
  _X_____X,________,
  X__XXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_59CB[ 28] = { /* code 59CB */
  __X_____,X_______,
  __X_____,X_______,
  __X____X,________,
  XXXXX__X,__X_____,
  _X__X_X_,___X____,
  _X__XXXX,XXXXX___,
  _X__X___,____X___,
  X___X___,________,
  _X__X_XX,XXXX____,
  __XX__X_,___X____,
  ___X__X_,___X____,
  __X_X_X_,___X____,
  _X__X_XX,XXXX____,
  X_____X_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_5F0F[ 28] = { /* code 5F0F */
  ________,X_X_____,
  ________,X__X____,
  ________,X_______,
  XXXXXXXX,XXXXX___,
  ________,X_______,
  ________,X_______,
  _XXXXX__,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,_X______,
  ___X____,_X__X___,
  ___XXXX_,__X_X___,
  XXXX____,___XX___,
  ________,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_65F6[ 28] = { /* code 65F6 */
  ________,__X_____,
  ________,__X_____,
  XXXX____,__X_____,
  X__X_XXX,XXXXX___,
  X__X____,__X_____,
  X__X____,__X_____,
  XXXX__X_,__X_____,
  X__X___X,__X_____,
  X__X___X,__X_____,
  X__X____,__X_____,
  XXXX____,__X_____,
  X__X____,__X_____,
  ________,__X_____,
  ________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_69DB[ 28] = { /* code 69DB */
  __X____X,__X_____,
  __X__X_X,__X_____,
  __X__X_X,__XXX___,
  XXXX_X_X,_X______,
  __X__X_X,X_X_____,
  __X__X_X,___X____,
  _XXX___X,___X____,
  _XX_X___,________,
  X_X__XXX,XXXX____,
  __X__X_X,_X_X____,
  __X__X_X,_X_X____,
  __X__X_X,_X_X____,
  __X__X_X,_X_X____,
  __X_XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_6A21[ 28] = { /* code 6A21 */
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X__XXX,XXXXX___,
  XXXX__X_,__X_____,
  __X__XXX,XXXX____,
  __X__X__,___X____,
  _XXX_XXX,XXXX____,
  _XX_XX__,___X____,
  X_X__XXX,XXXX____,
  __X_____,X_______,
  __X_XXXX,XXXXX___,
  __X____X,_X______,
  __X___X_,__X_____,
  __X_XX__,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_6B65[ 28] = { /* code 6B65 */
  ______X_,________,
  __X___X_,________,
  __X___XX,XXXX____,
  __X___X_,________,
  __X___X_,________,
  XXXXXXXX,XXXXX___,
  ________,________,
  ___X__X_,________,
  __X___X_,__X_____,
  _X____X_,_X______,
  ______X_,X_______,
  ______XX,________,
  ___XXX__,________,
  XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_6D41[ 28] = { /* code 6D41 */
  ________,X_______,
  _X______,_X______,
  __X__XXX,XXXXX___,
  ___X____,X_______,
  _______X,__X_____,
  X_____X_,___X____,
  _X___XXX,XXXXX___,
  ___X____,____X___,
  ___X__X_,X_X_____,
  __X___X_,X_X_____,
  __X___X_,X_X_____,
  _X____X_,X_X_____,
  _X___X__,X_X_X___,
  ____X___,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_7535[ 28] = { /* code 7535 */
  _____X__,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXX_____,
  X____X__,__X_____,
  X____X__,__X_____,
  XXXXXXXX,XXX_____,
  X____X__,__X_____,
  X____X__,__X_____,
  XXXXXXXX,XXX_____,
  X____X__,________,
  _____X__,___X____,
  _____X__,___X____,
  ______XX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_77ED[ 28] = { /* code 77ED */
  _X______,________,
  _X____XX,XXXX____,
  _XXXX___,________,
  X_X_____,________,
  __X___XX,XXXX____,
  __X___X_,___X____,
  __X___X_,___X____,
  XXXXX_X_,___X____,
  __X___XX,XXXX____,
  __X_____,________,
  _X_X__X_,___X____,
  _X__X__X,__X_____,
  _X__X___,________,
  X____XXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_8D1F[ 28] = { /* code 8D1F */
  ___X____,________,
  ___XXXXX,XXX_____,
  __X_____,__X_____,
  _X______,_X______,
  X_______,X_______,
  _XXXXXXX,XXXX____,
  _X______,___X____,
  _X____X_,___X____,
  _X____X_,___X____,
  _X____X_,___X____,
  _X___X_X,___X____,
  ____X___,XX______,
  __XX____,__XX____,
  XX______,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_8D77[ 28] = { /* code 8D77 */
  ___X____,________,
  ___X___X,XXXX____,
  _XXXXX__,___X____,
  ___X____,___X____,
  ___X____,___X____,
  XXXXXX_X,XXXX____,
  ___X___X,________,
  ___X___X,________,
  _X_XXX_X,____X___,
  _X_X___X,____X___,
  _X_X____,XXXXX___,
  _X_X____,________,
  X_XX____,________,
  X___XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_8DEF[ 28] = { /* code 8DEF */
  ________,X_______,
  _XXXX___,X_______,
  _X__X___,XXXX____,
  _X__X__X,___X____,
  _X__X_X_,X_X_____,
  _XXXX___,_X______,
  ___X____,X_X_____,
  _X_X__XX,___XX___,
  _X_XXX__,________,
  _X_X___X,XXXX____,
  _X_X___X,___X____,
  _X_XXX_X,___X____,
  XXX____X,XXXX____,
  _______X,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_8F7D[ 28] = { /* code 8F7D */
  ___X____,X_______,
  ___X____,X_X_____,
  _XXXXX__,X__X____,
  ___X____,X_______,
  XXXXXXXX,XXXXX___,
  __X_____,X_______,
  XXXXXXX_,X__X____,
  __X_____,X__X____,
  _X_X____,X_X_____,
  _XXXXX__,X_X_____,
  ___X____,_X__X___,
  XXXXXXX_,X_X_X___,
  ___X___X,___XX___,
  ___X__X_,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_8FC7[ 28] = { /* code 8FC7 */
  ________,__X_____,
  _X______,__X_____,
  __X_____,__X_____,
  __X_XXXX,XXXXX___,
  ________,__X_____,
  _____X__,__X_____,
  XXX___X_,__X_____,
  __X___X_,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,XXX_____,
  _X_X____,________,
  X___XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_8FDB[ 28] = { /* code 8FDB */
  ______X_,__X_____,
  _X____X_,__X_____,
  __X___X_,__X_____,
  __X_XXXX,XXXXX___,
  ______X_,__X_____,
  ______X_,__X_____,
  XXX___X_,__X_____,
  __X_XXXX,XXXXX___,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X__X__,__X_____,
  _X_X____,________,
  X___XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_95E8[ 28] = { /* code 95E8 */
  _X______,________,
  __X_XXXX,XXXX____,
  __X_____,___X____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  X_______,___X____,
  X_______,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_95F4[ 28] = { /* code 95F4 */
  _X______,________,
  __X_XXXX,XXXX____,
  __X_____,___X____,
  X_______,___X____,
  X__XXXXX,X__X____,
  X__X____,X__X____,
  X__X____,X__X____,
  X__XXXXX,X__X____,
  X__X____,X__X____,
  X__X____,X__X____,
  X__XXXXX,X__X____,
  X_______,___X____,
  X_______,___X____,
  X_______,_XXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_5145[ 28] = { /* code 5145 */
  _____X__,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  ____X___,________,
  ___X____,_X______,
  __X_____,__X_____,
  _XXXXXXX,XXXX____,
  ____X___,X__X____,
  ____X___,X_______,
  ____X___,X_______,
  ____X___,X_______,
  ___X____,X___X___,
  __X_____,X___X___,
  XX______,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_679C[ 28] = { /* code 679C */
  __XXXXXX,XXX_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __XXXXXX,XXX_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __XXXXXX,XXX_____,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  ____X_X_,X_______,
  ___X__X_,_X______,
  __X___X_,__X_____,
  XX____X_,___XX___,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_6D4B[ 28] = { /* code 6D4B */
  ________,____X___,
  _X__XXXX,X___X___,
  __X_X___,X___X___,
  ____X_X_,X_X_X___,
  X___X_X_,X_X_X___,
  _X__X_X_,X_X_X___,
  ____X_X_,X_X_X___,
  __X_X_X_,X_X_X___,
  __X_X_X_,X_X_X___,
  _X____X_,__X_X___,
  _X___X_X,____X___,
  X____X__,X___X___,
  X___X___,X___X___,
  ___X____,__XXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_7ED3[ 28] = { /* code 7ED3 */
  __X_____,X_______,
  __X_____,X_______,
  _X__XXXX,XXXXX___,
  X__X____,X_______,
  XXXX____,X_______,
  __X__XXX,XXXX____,
  _X______,________,
  X_______,________,
  XXXX_XXX,XXXX____,
  _____X__,___X____,
  _____X__,___X____,
  __XX_X__,___X____,
  XX___XXX,XXXX____,
  _____X__,___X____};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_8BD5[ 28] = { /* code 8BD5 */
  _X______,_X_X____,
  __X_____,_X__X___,
  __X_____,_X______,
  ____XXXX,XXXXX___,
  ________,_X______,
  XXX_____,_X______,
  __X__XXX,_X______,
  __X___X_,_X______,
  __X___X_,_X______,
  __X___X_,__X_____,
  __X_X_X_,__X_X___,
  __XX__XX,X_X_X___,
  __X_XXX_,___XX___,
  ________,____X___};

  GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_5173[ 28] = { /* code 5173 */
  ___X____,_X______,
  ____X___,_X______,
  ____X___,X_______,
  _XXXXXXX,XXXX____,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXX___,
  _____X_X,________,
  _____X_X,________,
  ____X___,X_______,
  ___X____,_X______,
  __X_____,__X_____,
  XX______,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_5F00[ 28] = { /* code 5F00 */
  _XXXXXXX,XXXX____,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  XXXXXXXX,XXXXX___,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  _X______,_X______,
  X_______,_X______};

GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_653E[ 28] = { /* code 653E */
  __X_____,X_______,
  ___X____,X_______,
  ________,X_______,
  XXXXXX__,XXXXX___,
  __X____X,___X____,
  __X___X_,X__X____,
  __XXXX__,X__X____,
  __X__X__,X__X____,
  __X__X__,X_X_____,
  __X__X__,X_X_____,
  __X__X__,_X______,
  _X___X__,X_X_____,
  _X___X_X,___X____,
  X__XX_X_,____X___};

  GUI_CONST_STORAGE unsigned char acGUI_FontHZ14_9501[ 28] = { /* code 9501 */
  ________,________,
  _____XXX,________,
  ____X___,X_______,
  ___XX___,XX______,
  ___X____,_X______,
  __XXXXXX,XXX_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __XXXXXX,XXX_____,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontHZ14_CharInfo[27] = {
   {  13,  13,   0,   1,  14, acGUI_FontHZ14_538B } /* code 538B */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_59CB } /* code 59CB */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_5F0F } /* code 5F0F */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_65F6 } /* code 65F6 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_69DB } /* code 69DB */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_6A21 } /* code 6A21 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_6B65 } /* code 6B65 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_6D41 } /* code 6D41 */
  ,{  12,  14,   1,   0,  14, acGUI_FontHZ14_7535 } /* code 7535 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_77ED } /* code 77ED */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_8D1F } /* code 8D1F */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_8D77 } /* code 8D77 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_8DEF } /* code 8DEF */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_8F7D } /* code 8F7D */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_8FC7 } /* code 8FC7 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_8FDB } /* code 8FDB */
  ,{  12,  14,   1,   0,  14, acGUI_FontHZ14_95E8 } /* code 95E8 */
  ,{  12,  14,   1,   0,  14, acGUI_FontHZ14_95F4 } /* code 95F4 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_5145 } /* code 5145 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_679C } /* code 679C */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_6D4B } /* code 6D4B */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_7ED3 } /* code 7ED3 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_8BD5 } /* code 8BD5 */
  , {  13,  14,   0,   0,  14, acGUI_FontHZ14_5173 } /* code 5173 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_5F00 } /* code 5F00 */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_653E } /* code 653E */
  ,{  13,  14,   0,   0,  14, acGUI_FontHZ14_9501 } /* code 9501 */
};
GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop27 = {
   0x9501 /* first character */
  ,0x9501 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  26] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop26 = {
   0x653E /* first character */
  ,0x653E /* last character  */
  ,&GUI_FontHZ14_CharInfo[  25] /* address of first character */
 ,&GUI_FontHZ14_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop25 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  24] /* address of first character */
  ,&GUI_FontHZ14_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop24 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  23] /* address of first character */
 ,&GUI_FontHZ14_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop23 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  22] /* address of first character */
  ,&GUI_FontHZ14_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop22 = {
   0x7ED3 /* first character */
  ,0x7ED3 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  21] /* address of first character */
  ,&GUI_FontHZ14_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop21 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontHZ14_CharInfo[  20] /* address of first character */
  ,&GUI_FontHZ14_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop20 = {
   0x679C /* first character */
  ,0x679C /* last character  */
  ,&GUI_FontHZ14_CharInfo[  19] /* address of first character */
  ,&GUI_FontHZ14_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop19 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  18] /* address of first character */
  ,&GUI_FontHZ14_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop18 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontHZ14_CharInfo[ 17] /* address of first character */
  ,&GUI_FontHZ14_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop17 = {
   0x95E8 /* first character */
  ,0x95E8 /* last character  */
  ,&GUI_FontHZ14_CharInfo[ 16] /* address of first character */
  ,&GUI_FontHZ14_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop16 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_FontHZ14_CharInfo[ 15] /* address of first character */
  ,&GUI_FontHZ14_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop15 = {
   0x8FC7 /* first character */
  ,0x8FC7 /* last character  */
  ,&GUI_FontHZ14_CharInfo[ 14] /* address of first character */
  ,&GUI_FontHZ14_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop14 = {
   0x8F7D /* first character */
  ,0x8F7D /* last character  */
  ,&GUI_FontHZ14_CharInfo[ 13] /* address of first character */
  ,&GUI_FontHZ14_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop13 = {
   0x8DEF /* first character */
  ,0x8DEF /* last character  */
  ,&GUI_FontHZ14_CharInfo[ 12] /* address of first character */
  ,&GUI_FontHZ14_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop12 = {
   0x8D77 /* first character */
  ,0x8D77 /* last character  */
  ,&GUI_FontHZ14_CharInfo[ 11] /* address of first character */
  ,&GUI_FontHZ14_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop11 = {
   0x8D1F /* first character */
  ,0x8D1F /* last character  */
  ,&GUI_FontHZ14_CharInfo[ 10] /* address of first character */
  ,&GUI_FontHZ14_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop10 = {
   0x77ED /* first character */
  ,0x77ED /* last character  */
  ,&GUI_FontHZ14_CharInfo[  9] /* address of first character */
  ,&GUI_FontHZ14_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop9 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  8] /* address of first character */
  ,&GUI_FontHZ14_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop8 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  7] /* address of first character */
  ,&GUI_FontHZ14_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop7 = {
   0x6B65 /* first character */
  ,0x6B65 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  6] /* address of first character */
  ,&GUI_FontHZ14_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop6 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  5] /* address of first character */
  ,&GUI_FontHZ14_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop5 = {
   0x69DB /* first character */
  ,0x69DB /* last character  */
  ,&GUI_FontHZ14_CharInfo[  4] /* address of first character */
  ,&GUI_FontHZ14_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop4 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontHZ14_CharInfo[  3] /* address of first character */
  ,&GUI_FontHZ14_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop3 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontHZ14_CharInfo[  2] /* address of first character */
  ,&GUI_FontHZ14_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop2 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontHZ14_CharInfo[  1] /* address of first character */
  ,&GUI_FontHZ14_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontHZ14_Prop1 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_FontHZ14_CharInfo[  0] /* address of first character */
  ,&GUI_FontHZ14_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHZ14 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,14 /* height of font  */
  ,14 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHZ14_Prop1}
  ,12 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,9 /* Height of capital characters */
};

